---
apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: deploy helm chart
description: deploys a helm chart using a standard repo
inputs:
  chart:
    description: chart name
    required: true
  repo:
    description: chart repository
    required: true
  namespace:
    description: namespace to deploy to
    required: true
  release:
    description: name of the release
    required: true
  version:
    description: version of the chart
    required: false

  
runs:
  using: composite
  steps:
    - id: deploy_chart
      name: Deploy Chart
      uses: docker://alpine/helm:latest
      shell: sh
      run: |
         _version=""
         printf "version is [${{ inputs.version }}]\n"
         printf "release is [${{ inputs.release }}]\n"
         printf "abc\n"
         if [ "${{ inputs.version }}" != "" ]; then
            _version="--version=${{ inputs.version }}"
         fi
         printf "_version is [$_version]"
         printf "the derived version is $_version"
         repo_tmp=$(echo ${{ inputs.chart }} |cut -d/ -f 1)
         helm repo add $repo_tmp ${{ inputs.repo }} 
         
         helm repo list
         helm repo update
         echo "version is [${{ inputs.version }}]"
         printf "about to run [helm upgrade --install ${{ inputs.release }}  ${{ inputs.chart }} $_version -n ${{ inputs.namespace }}]\n"
         helm upgrade --install ${{ inputs.release }}  ${{ inputs.chart }} $_version -n ${{ inputs.namespace }}
         
